resolver: lts-14.3
packages:
  - asterius
  - binaryen
  - ghc-toolkit
  - inline-js/inline-js-core
  - npm-utils
  - wabt
  - wasm-toolkit
ghc-build: standard
setup-info:
  ghc:
    linux64:
      8.6.5:
        url: https://6484-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: 36a9946e4078316c127b4fe9ff635e4c18cf9a6b845e1ffdcac6c7ff1ca3c1f2
    macosx:
      8.6.5:
        url: https://6483-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        sha256: 21c47c4208ead30a6c808279b8d36a676458e8621dd7e3e2ae392cba9d0c4710
