resolver: lts-14.3
packages:
  - asterius
  - binaryen
  - ghc-toolkit
  - inline-js/inline-js-core
  - npm-utils
  - wabt
  - wasm-toolkit
ghc-build: standard
setup-info:
  ghc:
    linux64:
      8.6.5:
        url: https://6507-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: 3243867786e5920ceb9f42f12a8e7270293097018ed5d32b7c8559551146e442
    macosx:
      8.6.5:
        url: https://6508-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        sha256: c1615bcc78443f1fe466fb44b685850341e25a7aad405b31f930014cbf981870
