name: asterius
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

flags:
  binaryen:
    default: true
    manual: true

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - test/array/**/*.hs
  - test/fib/**/*.hs
  - test/jsffi/**/*.hs
  - test/jsffi/jsffi.mjs
  - test/rtsapi/**/*.hs
  - test/rtsapi/rtsapi.mjs
  - test/stableptr/**/*.hs
  - test/todomvc/**/*.hs
  - test/todomvc/**/*.html
  - test/teletype/**/*.hs
  - test/bytearray/**/*.hs
  - test/bytearraymini/**/*.hs
  - test/bigint/**/*.hs
  - test/cloudflare/**/*.hs
  - test/cloudflare/cloudflare.mjs
  - test/nomain/**/*.hs
  - test/ghc-testsuite/**/*.hs
  - test/ghc-testsuite/**/*.stdout
  - test/exception/**/*.hs
  - test/regression60/**/*.hs
  - test/sizeof_md5context/**/*.hs
  - test/largenum/**/*.hs

data-files:
  - rts/*.mjs
  - boot-init.sh
  - boot.sh

custom-setup:
  dependencies:
    - base
    - Cabal
    - ghc-toolkit

ghc-options: -Wall

dependencies:
  - base
  - binary
  - bytestring
  - Cabal
  - containers
  - deepseq
  - directory
  - filepath
  - ghc
  - ghc-boot
  - ghc-prim
  - ghc-toolkit
  - ghci
  - inline-js-core
  - libiserv
  - mtl
  - npm-utils
  - parsec
  - process
  - template-haskell
  - transformers
  - wasm-toolkit

when:
  - condition: flag(binaryen)
    dependencies:
      - binaryen
    cpp-options: -DBINARYEN

library:
  source-dirs: src
  other-modules: Paths_asterius
  other-extensions:
    - DeriveGeneric
    - DeriveDataTypeable
    - FlexibleContexts
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MagicHash
    - NamedFieldPuns
    - OverloadedLists
    - OverloadedStrings
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - StrictData
    - TemplateHaskell
    - TypeFamilies
    - UnboxedTuples

executables:
  ahc:
    source-dirs: app
    main: ahc.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  ahc-pkg:
    source-dirs: app
    main: ahc-pkg.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  ahc-boot:
    source-dirs: app
    main: ahc-boot.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  ahc-link:
    source-dirs: app
    main: ahc-link.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  ahc-ld:
    source-dirs: app
    main: ahc-ld.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  ahc-dist:
    source-dirs: app
    main: ahc-dist.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  ahc-cabal:
    source-dirs: app
    main: ahc-cabal.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

tests:
  fib:
    source-dirs: test
    main: fib.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  jsffi:
    source-dirs: test
    main: jsffi.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  array:
    source-dirs: test
    main: array.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  stableptr:
    source-dirs: test
    main: stableptr.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  rtsapi:
    source-dirs: test
    main: rtsapi.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  todomvc:
    source-dirs: test
    main: todomvc.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  teletype:
    source-dirs: test
    main: teletype.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  bytearray:
    source-dirs: test
    main: bytearray.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  bytearraymini:
    source-dirs: test
    main: bytearraymini.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  bigint:
    source-dirs: test
    main: bigint.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  cloudflare:
    source-dirs: test
    main: cloudflare.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  nomain:
    source-dirs: test
    main: nomain.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  exception:
    source-dirs: test
    main: exception.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  ghc-testsuite:
    source-dirs: test
    main: ghc-testsuite.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius
      - tasty
      - tasty-hunit
      - cassava
      - optparse-applicative

  ghc-testsuite-with-ghc:
    source-dirs: test
    main: ghc-testsuite-with-ghc.hs
    ghc-options: -threaded -rtsopts
    dependencies: []

  sizeof_md5context:
    source-dirs: test
    main: sizeof_md5context.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  regression60:
    source-dirs: test
    main: regression60.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  largenum:
    source-dirs: test
    main: largenum.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius

  th:
    source-dirs: test
    main: th.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - asterius
